kind: Deployment
metadata:
  name: mywebsite
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 50
  template:
    metadata:
      name: xyz
      labels:
        app: webserver
    spec:
      containers:
        - name: sdfdf
          image: nginx
