apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mywebsite
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 20
  template:
    metadata:
      name: xyz
      labels:
        app: webserver
    spec:
      containers:
      - name: sdfdf
        image: httpd